@startuml
hide circle
skinparam classAttributeIconSize 0
<style>
classDiagram {
  class {
      ' attributes and methods
      FontColor black
      BackgroundColor lightgray
      ' class name
      header {
        ' FontSize 20
        BackgroundColor yellow
        FontColor green
        FontStyle bold
      }
  }
}
</style>

SkinParam {
    NodeSep 200 ' horizontal spacing
    RankSep 200 ' vertical spacing
}

class Class1
{
    + check : int
}
diamond         diamond
<>              diamond_short_form
entity          entity
enum            enum
exception       exception
interface       interface
metaclass       metaclass
protocol        protocol
stereotype      stereotype
struct          struct
@enduml