@startuml test
hide circle
hide empty members
'skinparam classAttributeIconSize 0
skinparam style strictuml
skinparam groupInheritance 2
'skinparam linetype ortho
'skinparam linetype polyline
<style>
classDiagram {
  class {
    '-attributes and methods-
    'FontSize 14
    'FontColor black
    'BackgroundColor #fefece
    BackgroundColor #f0fff0
    'RoundCorner 0
    '-class name-
    header {
      'FontSize 12
      'FontColor Black
      FontStyle bold
      BackgroundColor YellowGreen
    }
  }
  note {
    BackgroundColor Yellow
  }
}
</style>

legend top left
  Contstructors without parameters are ommited in this diagram
endlegend

''note "Test1" as Note1
'note "Test2" as Note2
'Note1 .. Class1
'Note1 . Class2

class Activity {
  # _name : string
  # _description : string
  # _duration : int
  # _animation : Animation
  # _countdown : Countdown
  + DisplayStartingMessage() : void
  + DisplayEndingMessage() : void
}


class BreathingActivity {
  + RunActivity : void
}

class ReflectionActivity {
  - _reflectionPromptGenerator :\n ReflectionPromptGenerator
  - _reflectionQuestionGenerator :\n ReflectionQuestionGenerator
  + RunActivity() : void
}

class ListingActivity {
  - _listingPromptGenerator :\n ListingPromptGenerator
  - _itemCount : int
  + RunActivity() : void
}

class ReflectionPromptGenerator {
  - _reflectionPrompts : List<string>
  + GetPrompt() : string
}

class ReflectionQuestionGenerator {
  - _reflectionQuestions : List<string>
  + GetQuestion() : string
}

class ListingPromptGenerator {
  - _listingPrompts : List<string>
  + GetPrompt() : string
}
together{
class Animation {
  + Display(duration : int) : void
}

note top of Animation: Helper class
}

class Countdown {
  + Display(duration : int) : void
}




Activity <|-- BreathingActivity
Activity <|-- ReflectionActivity
Activity <|-- ListingActivity
ReflectionActivity <.. ReflectionPromptGenerator
ReflectionActivity <.. ReflectionQuestionGenerator
ListingActivity <.. ListingPromptGenerator
Activity <.left. Animation
Activity <.right. Countdown

@enduml